library(shiny)
library(networkD3)

fluidPage(title = "Beinecke modernist correspondence network",

	br(),

	sidebarPanel(
		h3("Beinecke modernist correspondence network"),
		p("This interactive graph shows shared correspondents of the modernist writers ", strong("Ezra Pound, H.D., Gertrude Stein and William Carlos Williams"), " based on ", a("collections of letters", href = "beinecke.library.yale.edu/collections/curatorial-areas/american-literature#Modernism"), " held at Yale University's Beinecke Library. Colours are generated by the ", em(a("Walktrap", href = "http://arxiv.org/abs/physics/0512106")), " algorithm. Weights are calculated using the total volume (in folders) of the letters held for each correspondent and the time period that they span."),
		p(strong("Click and drag"), " to move the graph, ", strong("mouse-over"), " nodes to view the people or organisations that they represent, and ", strong("pinch or use the scroll wheel"), " to zoom."),
		sliderInput("weight", "% of less important correspondents to exclude", min = 0, max = 99.6, value = 75, round = 0),
		sliderInput("charge", "Strength of attractive force", min = -1000, max = 0, value = -400, round = 0),
        checkboxInput("colours", "Community colouring on/off", value = TRUE),
		p("Created by ", a("Louis Goddard", href = "http://louisg.xyz"), "/", a("Source code", href = "https://github.com/ltrgoddard/beinecke")),
		p("Powered by ", a("R", href = "https://www.r-project.org/"), "/", a("D3.js", href = "https://d3js.org/"), "/", a("Shiny", href = "http://shiny.rstudio.com/"), "/", a("igraph", href = "http://igraph.org/"), "/", a("networkD3", href = "https://christophergandrud.github.io/networkD3/"))
	),

	mainPanel(
		forceNetworkOutput("force", height = 700)
	)
)
